[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via-ir = true
solc = "0.8.28"
evm_version = "cancun"
auto_detect_remappings = false
remappings = [
    "forge-std/=lib/forge-std/src/",
    "openzeppelin/=lib/openzeppelin-contracts/contracts/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
