[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.26"
via-ir = true
remappings = [
    "lib/uniswap-universal-router/:@uniswap/v3-core/contracts/=lib/uniswap-v3-core/contracts/",
    "lib/uniswap-universal-router/:@uniswap/v4-periphery/src/=lib/uniswap-v4-periphery/src/",
    "lib/uniswap-v3-periphery/:@openzeppelin/contracts/token/ERC721/=lib/openzeppelin/contracts/interfaces/",
    "lib/uniswap-v4-periphery/:@openzeppelin/contracts/=lib/openzeppelin/contracts/",
    "lib/uniswap-v4-periphery/:@uniswap/v4-core/=lib/uniswap-v4-periphery/lib/v4-core/",
    "@forge-std/=lib/forge-std/src/",
    "@across/=lib/across/contracts/",
    "@openzeppelin/=lib/openzeppelin/contracts/",
    "@uniswap-permit2/=lib/uniswap-permit2/src/",
    "@uniswap-universal-router/=lib/uniswap-universal-router/contracts/",
    "@uniswap-v3-core/=lib/uniswap-v3-core/contracts",
    "@uniswap-v3-periphery/=lib/uniswap-v3-periphery/contracts/",
    "@uniswap-v4-core/=lib/uniswap-v4-periphery/lib/v4-core/src/",
    "@uniswap-v4-periphery/=lib/uniswap-v4-periphery/src/"
]
fs_permissions = [{ access = "read", path = "./broadcast" }]

[etherscan]
mainnet = { key = "${MAINNET_ETHERSCAN_API_KEY}" }
10 = { key = "${OPTIMISM_ETHERSCAN_API_KEY}" }
130 = { key = "${UNICHAIN_ETHERSCAN_API_KEY}", url = "${UNICHAIN_ETHERSCAN_API_URL}" }
42161 = { key = "${ARBITRUM_ETHERSCAN_API_KEY}" }
8453 = { key = "${BASE_ETHERSCAN_API_KEY}" }
